# Enable C++
language: cpp

# Compiler
compiler: gcc

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build steps
script:
  - rm -rf build
  - mkdir build
  - cd build
  - pwd && cmake ..
  - pwd && make
  - pwd && make test

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
